#!/usr/bin/env node
/**
 * slice-modules.mjs — cut a webpack bundle's modules out verbatim, by id.
 *
 * The flat-bundle projects needed extract-source.mjs: a line-range slicer with a
 * hand-maintained slice table, because module boundaries had to be RECONSTRUCTED
 * and a wrong boundary is a silent error. Here the packer wrote the boundaries
 * down, so the slice table is just a list of module ids and the tool can verify
 * itself against the map.
 *
 * ⛔ Byte-verbatim. Each module's text is copied between the offsets the parser
 * reported; nothing is retyped, reformatted or corrected (porting-discipline.md
 * §1.3). The generated file re-declares the webpack runtime so the slice runs on
 * its own, and that runtime is the ONE thing here that is transcribed rather
 * than sliced — it is registered as such in the header.
 *
 *   node scripts/slice-modules.mjs --closure docs/slice-closure.json
 *                                [--map docs/webpack-map.json]
 *                                [--in mirror/_pretty/main.built.js]
 *                                [--out port/_gen/tween.gen.js] [--check]
 */
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { createHash } from "node:crypto";
import path from "node:path";

const args = process.argv.slice(2);
const flag = (n, d) => { const i = args.indexOf("--" + n); return i >= 0 && args[i + 1] !== undefined ? args[i + 1] : d; };
const CHECK = args.includes("--check");
const IN = path.resolve(flag("in", "mirror/_pretty/main.built.js"));
const MAP = path.resolve(flag("map", "docs/webpack-map.json"));
const CLOSURE = path.resolve(flag("closure", "docs/slice-closure.json"));
const OUT = path.resolve(flag("out", "port/_gen/tween.gen.js"));

const src = await readFile(IN, "utf8");
const lines = src.split("\n");
const map = JSON.parse(await readFile(MAP, "utf8"));
const closure = JSON.parse(await readFile(CLOSURE, "utf8"));
const byId = new Map(map.modules.map((m) => [m.id, m]));

// ⛔ The map is an input, and an input can go stale. Re-derive the source's
// sha256 and refuse if it moved — a slice table pointing into a file that has
// changed is the F26 failure (a recorded green whose input was regenerated).
const srcHash = createHash("sha256").update(src).digest("hex");

const wanted = closure.modules.filter((id) => byId.has(id));
const missing = closure.modules.filter((id) => !byId.has(id));
if (missing.length) {
  console.error(`FATAL: ${missing.length} module id(s) in the closure are not in the map: ${missing.slice(0, 5).join(", ")}`);
  console.error(`       Re-run webpack-map.mjs, or the closure was computed against a different bundle.`);
  process.exit(5);
}

// Emit in SOURCE ORDER — the packer's own order, which is also the order the
// runtime would evaluate them in if it walked the container.
const mods = wanted.map((id) => byId.get(id)).sort((a, b) => a.startLine - b.startLine);

const parts = [];
for (const m of mods) {
  const text = lines.slice(m.startLine - 1, m.endLine).join("\n");
  parts.push({ id: m.id, from: m.startLine, to: m.endLine, lines: m.lines, text });
}

const header = [
  `// AUTO-GENERATED by scripts/slice-modules.mjs — DO NOT EDIT BY HAND.`,
  `//`,
  `// Verbatim webpack modules cut from ${path.relative(process.cwd(), IN)}`,
  `//   sha256 ${srcHash}`,
  `// ${parts.length} module(s), ${parts.reduce((t, p) => t + p.lines, 0)} source lines, in packer order.`,
  `//`,
  `// Regenerate:  node scripts/slice-modules.mjs --closure ${path.relative(process.cwd(), CLOSURE)}`,
  `// Verify:      node scripts/slice-modules.mjs --closure ${path.relative(process.cwd(), CLOSURE)} --check`,
  `//`,
  `// ⛔ Nothing below the runtime was retyped, reformatted or corrected. Source-site`,
  `// bugs, dead code and odd spellings are present ON PURPOSE — they are the port.`,
  `//`,
  `// ⚠ REGISTERED DEVIATION: the webpack runtime below is TRANSCRIBED, not sliced.`,
  `// The original is one closure wrapping the whole 597-module container; carrying`,
  `// it verbatim would carry all 597. This is the smallest re-implementation that`,
  `// preserves the contract the modules were compiled against: require by id,`,
  `// memoised exports, module/exports objects. Registered in REBUILD_PLAN §6 D4.`,
  ``,
  `const __modules = {};`,
  `const __cache = {};`,
  `function __req(id) {`,
  `  if (__cache[id]) return __cache[id].exports;`,
  `  const m = (__cache[id] = { i: id, l: false, exports: {} });`,
  `  __modules[id].call(m.exports, m, m.exports, __req);`,
  `  m.l = true;`,
  `  return m.exports;`,
  `}`,
  `__req.d = (exports, name, getter) => { if (!Object.prototype.hasOwnProperty.call(exports, name)) Object.defineProperty(exports, name, { enumerable: true, get: getter }); };`,
  `__req.r = (exports) => { if (typeof Symbol !== "undefined" && Symbol.toStringTag) Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" }); Object.defineProperty(exports, "__esModule", { value: true }); };`,
  `__req.n = (mod) => { const g = mod && mod.__esModule ? () => mod.default : () => mod; __req.d(g, "a", g); return g; };`,
  `__req.o = (obj, prop) => Object.prototype.hasOwnProperty.call(obj, prop);`,
  ``,
  `Object.assign(__modules, {`,
].join("\n");

const body = parts.map((p) =>
  `\n// ===== ${path.relative(process.cwd(), IN)} L${p.from}-L${p.to}  (${p.lines} lines) =====\n${p.text}`
).join("\n");

const footer = [
  ``,
  `});`,
  ``,
  `export { __req, __modules };`,
  `export default __req;`,
  ``,
].join("\n");

const out = header + body + footer;

if (CHECK) {
  const have = await readFile(OUT, "utf8").catch(() => null);
  if (have === null) { console.error(`FATAL: ${path.relative(process.cwd(), OUT)} does not exist.`); process.exit(1); }
  const same = have === out;
  console.log(`=== slice-modules --check ===`);
  console.log(`  ${parts.length} module(s) re-sliced from a source at sha256 ${srcHash.slice(0, 16)}`);
  console.log(same ? `  ok   the generated file is byte-identical to a fresh slice` : `  FAIL the generated file differs from a fresh slice`);
  process.exit(same ? 0 : 1);
}

await mkdir(path.dirname(OUT), { recursive: true });
await writeFile(OUT, out);
console.log(`=== slice-modules ===`);
console.log(`  ${parts.length} module(s), ${parts.reduce((t, p) => t + p.lines, 0)} verbatim source lines`);
console.log(`  source sha256 ${srcHash.slice(0, 16)}`);
console.log(`  -> ${path.relative(process.cwd(), OUT)}`);
